Implement pkg-config inline as it's absent in vanilla os/x

diff --git a/bin/eups_pkg-config b/bin/eups_pkg-config
--- a/bin/eups_pkg-config
+++ b/bin/eups_pkg-config
@@ -2,6 +2,58 @@
 #
 # Run pkg-config for a product that's set up
 #
+cflags=0
+libs=0
+function pkg_config {
+    case $1 in
+	-*)
+	    ;;
+	*)
+	product=$1; shift
+	if [ X$product = X ]; then
+	    echo "Please specify a product" >&2
+	    exit 1
+	fi;;
+    esac
+
+    while [ X$1 != X ]; do
+	case $1 in
+	    --cflags)
+		cflags=1;;
+	    --libs)
+		libs=1;;
+	    --usage|-*)
+		cat <<'EOF'
+(N.b. I am eups's implemention as real pkg-config is absent on some platforms)
+   --cflags	Print product's compiler flags
+   --libs		Print product's loader flags
+   --usage	Print this message
+EOF
+		exit 1;;
+	esac
+	shift
+    done
+    
+    pcfile=""
+    for d in $(echo $PKG_CONFIG_PATH | sed -e 's/:/ /g'); do
+	if [ -f $d/$product.pc ]; then
+	    pcfile=$d/$product.pc
+	fi
+    done
+
+    if [ X$pcfile = X ]; then
+	echo "I cannot find $product.pc on \$PKG_CONFIG_PATH" >&2
+	exit 1
+    fi
+
+    if [ $cflags = 1 ]; then
+	cat $pcfile | sed -n -e 's/\$\$/\$/g' -e 's/^Cflags: *//p'
+    fi
+    if [ $libs = 1 ]; then
+	cat $pcfile | sed -n -e 's/\$\$/\$/g' -e 's/^Libs: *//p'
+    fi
+}
+
 if [ X"$1" = X"-h" -o X"$1" = X"--help" ]; then
    cat >&2 <<EOF
 Run pkg-config on a product that's currently setup
@@ -10,7 +62,7 @@ Usage:
 
 All pkg-config options are passed through:
 EOF
-   pkg-config --usage
+   pkg_config --usage
    exit 1
 fi
 
@@ -52,5 +104,5 @@ export PKG_CONFIG_PATH
 # The sed works around an old bug in pkg-config
 # I filed a Debian bug report (378570) and it's fixed in the next release, 0.21-1
 #
-pkg-config $product "$@" | sed -e 's/%/$/g'
+pkg_config $product "$@" | sed -e 's/%/$/g'
 
